### ISSUE TITLE
st_envelope/st_extent

### ISSUE THREAD

**Issue by bertt** [bertt/i3dm.export#1]
@tebben can we use a simpler geometry to replace polygon in the query? like st_envelope/st_extent, it should be more performant.

https://github.com/bertt/i3dm.export/blob/bb8d551d72cf3a7b7d2c9fd1023b3ab02d362b61/src/BoundingBoxRepository.cs#L13

**Comment by tebben** [comment]
Using envelop looks better but I am not sure if this will result in increased performance since it is a simple polygon anyway. Updated and tested the new query, looks like it works correctly.  

https://github.com/bertt/i3dm.export/commit/ac863e5726daede48b05422a431ffa5c8708a7a2
